### ISSUE TITLE
Changefeed metadata is not cleaned up as expected 24 hours after removing a changefeed by CLI

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#1968] opened 2021-06-07 05:21 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- Remove changefeed "replication-task-1" before 2021-06-06T09:45.
- After more than 24 hours, create another changefeed with name "replication-task-1".

2. What did you expect to see?

- changefeed created successfully.

3. What did you see instead?

- Failed to create changefeed named "replication-task-1".

![image](https://user-images.githubusercontent.com/78345569/120962572-93937800-c792-11eb-9dff-27127397e1cc.png)

![image](https://user-images.githubusercontent.com/78345569/120962860-216f6300-c793-11eb-9f23-4102c6b5cd26.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        5.0.2
        ```

    - TiCDC version (execute `cdc version`):

        ```
       5.0.2
        ```

**Comment by sdojjy** [comment] 2022-09-07 06:45
Not able to reproduce in the test case, close it now. Reopen it if can reproduce it one day.

**Closed by sdojjy** 2022-09-07 06:45 UTC
Labels: type/bug, difficulty/easy, severity/moderate, area/ticdc
