### ISSUE TITLE
dm job master accesses an invalid memory address

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tiflow#7555] opened 2022-11-08 13:11 UTC
### What did you do?

1. submit a dm job to engine
2. kill executor, kill master
3. restart master and executor
4. query the previous dm job

### What did you expect to see?

dm job resume normally

### What did you see instead?

```
http: panic serving 172.31.52.193:53156: runtime error: invalid memory address or nil pointer dereference
goroutine 375 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1850 +0xbf
panic({0x3393cc0, 0x68133e0})
        runtime/panic.go:890 +0x262
github.com/pingcap/tiflow/engine/jobmaster/dm/metadata.(*MetaData).JobStore(...)
        github.com/pingcap/tiflow/engine/jobmaster/dm/metadata/metadata.go:49
github.com/pingcap/tiflow/engine/jobmaster/dm.(*JobMaster).QueryJobStatus(0xc00075c600, {0x4265de8?, 0xc000ed7dc0}, {0x0, 0x0, 0x0})
        github.com/pingcap/tiflow/engine/jobmaster/dm/api.go:50 +0x65
github.com/pingcap/tiflow/engine/jobmaster/dm.(*JobMaster).DMAPIGetJobStatus(0x391ad17?, 0xc000d2ab00, {0x450001?})
        github.com/pingcap/tiflow/engine/jobmaster/dm/openapi.go:60 +0x74
github.com/pingcap/tiflow/engine/jobmaster/dm/openapi.(*ServerInterfaceWrapper).DMAPIGetJobStatus(0xc000eacc30, 0xc000d2ab00)
        github.com/pingcap/tiflow/engine/jobmaster/dm/openapi/gen.server.go:258 +0x24a
github.com/gin-gonic/gin.(*Context).Next(...)
        github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/pingcap/tiflow/engine/jobmaster/dm.terrorHTTPErrorHandler.func1(0xc000d2ab00)
        github.com/pingcap/tiflow/engine/jobmaster/dm/openapi.go:72 +0x42
github.com/gin-gonic/gin.(*Context).Next(...)
        github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000e036c0, 0xc000d2ab00)
        github.com/gin-gonic/gin@v1.7.4/gin.go:489 +0x63e
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000e036c0, {0x4261c00?, 0xc001476620}, 0xc000d2a900)
        github.com/gin-gonic/gin@v1.7.4/gin.go:445 +0x1c5
github.com/pingcap/tiflow/engine/executor.(*jobAPIServer).ServeHTTP(0xc001141af0?, {0x4261c00, 0xc001476620}, 0xc000d2a900)
        github.com/pingcap/tiflow/engine/executor/openapi.go:45 +0x56
net/http.(*ServeMux).ServeHTTP(0x0?, {0x4261c00, 0xc001476620}, 0xc000d2a900)
        net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xc0011323c0?}, {0x4261c00, 0xc001476620}, 0xc000d2a900)
        net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000ba4fa0, {0x4265e90, 0xc00089b980})
        net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x4db
2022/11/08 13:00:02 http: panic serving 172.31.52.193:53164: runtime error: invalid memory address or nil pointer dereference
goroutine 378 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1850 +0xbf
panic({0x3393cc0, 0x68133e0})
        runtime/panic.go:890 +0x262
github.com/pingcap/tiflow/engine/jobmaster/dm/metadata.(*MetaData).JobStore(...)
        github.com/pingcap/tiflow/engine/jobmaster/dm/metadata/metadata.go:49
github.com/pingcap/tiflow/engine/jobmaster/dm.(*JobMaster).QueryJobStatus(0xc00075c600, {0x4265de8?, 0xc00113a400}, {0x0, 0x0, 0x0})
        github.com/pingcap/tiflow/engine/jobmaster/dm/api.go:50 +0x65
github.com/pingcap/tiflow/engine/jobmaster/dm.(*JobMaster).DMAPIGetJobStatus(0x391ad17?, 0xc000d2ad00, {0x450001?})
        github.com/pingcap/tiflow/engine/jobmaster/dm/openapi.go:60 +0x74
github.com/pingcap/tiflow/engine/jobmaster/dm/openapi.(*ServerInterfaceWrapper).DMAPIGetJobStatus(0xc000eacc30, 0xc000d2ad00)
        github.com/pingcap/tiflow/engine/jobmaster/dm/openapi/gen.server.go:258 +0x24a
github.com/gin-gonic/gin.(*Context).Next(...)
        github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/pingcap/tiflow/engine/jobmaster/dm.terrorHTTPErrorHandler.func1(0xc000d2ad00)
        github.com/pingcap/tiflow/engine/jobmaster/dm/openapi.go:72 +0x42
github.com/gin-gonic/gin.(*Context).Next(...)
        github.com/gin-gonic/gin@v1.7.4/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000e036c0, 0xc000d2ad00)
        github.com/gin-gonic/gin@v1.7.4/gin.go:489 +0x63e
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000e036c0, {0x4261c00?, 0xc001476700}, 0xc000d2ac00)
        github.com/gin-gonic/gin@v1.7.4/gin.go:445 +0x1c5
github.com/pingcap/tiflow/engine/executor.(*jobAPIServer).ServeHTTP(0xc001141af0?, {0x4261c00, 0xc001476700}, 0xc000d2ac00)
        github.com/pingcap/tiflow/engine/executor/openapi.go:45 +0x56
net/http.(*ServeMux).ServeHTTP(0x0?, {0x4261c00, 0xc001476700}, 0xc000d2ac00)
        net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0xc001133020?}, {0x4261c00, 0xc001476700}, 0xc000d2ac00)
        net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000ba5040, {0x4265e90, 0xc00089b980})
        net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x4db
[2022/11/08 13:00:06] [info] binlogsyncer.go:164 create BinlogSyncer with config {429533538 mysql tiflow-test-upstream.cmologbrh0ti.us-west-2.rds.amazonaws.com 3306 tiflowtest    false false <nil> false +00:00 false 0 30s 1m0s 1 true true 0 <nil> 0xc001efb0e0 0x77d040}
[2022/11/08 13:00:06] [info] binlogsyncer.go:400 begin to sync binlog from position (mysql-bin-changelog.005375, 376)
[2022/11/08 13:00:06] [info] binlogsyncer.go:816 rotate to (mysql-bin-changelog.005375, 376)
[2022/11/08 13:00:06] [info] binlogsyncer.go:816 rotate to (mysql-bin-changelog.005376, 4)
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
Release Version: v6.4.0-master
Git Commit Hash: 8017277ef8e2ec628ca952dd398087ded2b2b5f5
Git Branch: master
UTC Build Time: 2022-11-02 07:10:50
Go Version: go version go1.19.2 linux/amd64
Failpoint Build: false
```

**Comment by lance6716** [comment] 2022-11-08 13:30
Can you provide the log? I guess it's caused by API comes before jobmaster's InitImpl
@CharlesCheung96

**Comment by lance6716** [comment] 2022-11-08 13:33
maybe we should let OnOpenAPIInitialized be called after InitImpl? it's common that the jobmaster can't serve API before Init

@amyangfei

**Comment by amyangfei** [comment] 2022-11-09 03:31
> maybe we should let OnOpenAPIInitialized be called after InitImpl? it's common that the jobmaster can't serve API before Init
> 
> @amyangfei

It depends on when does job manager believes that job master is online, in current implement the init procedure of a job master(or worker) is 
- doPreInit
- Business logic InitImpl
- doPostInit 

The heartbeat goroutine starts in `doPreInit` and job manager will treat the job master online immediately when the first heartbeat message arrives. And then job manager could forward OpenAPI to this job master.

**Comment by amyangfei** [comment] 2022-11-09 05:56
> > maybe we should let OnOpenAPIInitialized be called after InitImpl? it's common that the jobmaster can't serve API before Init
> > @amyangfei
> 
> It depends on when does job manager believes that job master is online, in current implement the init procedure of a job master(or worker) is
> 
> * doPreInit
> * Business logic InitImpl
> * doPostInit
> 
> The heartbeat goroutine starts in `doPreInit` and job manager will treat the job master online immediately when the first heartbeat message arrives. And then job manager could forward OpenAPI to this job master.

I remember why we put heartbeat goroutine before `InitImpl`, because `InitImpl` could cost long time than heartbeat timeout, which will cause master disconnects worker.

**Comment by amyangfei** [comment] 2022-11-09 07:16
Maybe there are two ways
- Change the timing of `OnOpenAPIInitialized`, don't call `OnOpenAPIInitialized` until `InitImpl` finishes. In this way the forward API from tiflow master to dm job master may meet 404. But it seems not easy to implement this in current framework.
- Add a switch in DM logic, all forward API will return error if DM is not ready(InitImpl doesn't finish).

**Comment by gozssky** [comment] 2022-11-09 10:35
`InitImpl` is required by framework logic. So I think it's reasonable to initialize openapi handler after the job is initialized. I will work on solving this issue.

**Comment by gozssky** [comment] 2022-11-15 08:13
The bug mentioned by this issue should be fixed by https://github.com/pingcap/tiflow/pull/7587. There might be a better solution for this issue, we can create a new issue when we are ready to optimize the solution.

**Closed by gozssky** 2022-11-15 08:13 UTC
Labels: type/bug, severity/minor, area/engine
