### ISSUE TITLE
TiCDC Sink AWS msk，when msk deleted，changefeed status not change from normal to error

### ISSUE THREAD

**Issue by cchenkey** [pingcap/tiflow#6632] opened 2022-08-05 07:09 UTC
### What did you do?

1.create a changefeed to aws msk，msk use no password auth， cdc version 6.1.0 commit hash：9f5e3cea2fae0a3dce6cc5ca79e3bcd654b8aa99
2.when changefeed status become normal，delete msk
3.changefeed status will not change from normal to error，and checkpoint tso still Increase
4.use ticdc openapi "/ticdc/api/v1/changefeeds?state=all" to query cdc infomatation

### What did you expect to see?

when msk deleted，changefeed status will change from normal to error

cdc log：
[2022/08/05 06:05:32.877 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=122.304762ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:37.755 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=129.081635ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:37.875 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=120.603699ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:42.754 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=128.16293ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:42.882 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=127.989457ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:47.751 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=124.898398ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:47.879 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=124.847077ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:52.749 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=122.820419ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:52.877 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=122.259793ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:57.749 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=123.823242ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:05:57.886 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=131.053111ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:02.765 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=139.22416ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:02.891 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=136.628889ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:04.761 +00:00] [INFO] [middleware.go:41] [/api/v1/changefeeds] [status=200] [method=GET] [path=/api/v1/changefeeds] [query="state=all"] [ip=10.250.24.15] [user-agent=Go-http-client/1.1] [] [duration=560.723189ms]
[2022/08/05 06:06:07.759 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=133.377067ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:07.882 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=128.061316ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:12.749 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=123.276474ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:12.877 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=122.006566ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:17.745 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=119.38643ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:17.875 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=processor] [duration=119.890856ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]
[2022/08/05 06:06:22.747 +00:00] [WARN] [metrics.go:233] ["kafka cluster unreachable, use historical brokers to collect kafka broker level metrics"] [namespace=default] [changefeed=changefeed-60053] [role=owner] [duration=120.74206ms] [error="kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"]

query cdc openapi [curl -X GET http://127.0.0.1:8301/api/v1/changefeeds?state=all]  log: 
["cdc task info: {ID:changefeed-60053 State:normal CpTso:435075059278938114 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435075049042214916 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435075039329517575 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435075029355200523 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435075019393728515 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435075009157005317 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074998920282118 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074988683296776 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074978446573579 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074969533677573 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074959821504519 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074949846925321 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074940147335170 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074929910874115 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074919673888776 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074909175283720 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074898676154377 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074888977088514 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074878477959172 Error:{Code: Message:}}"]

["cdc task info: {ID:changefeed-60053 State:normal CpTso:435074867979091975 Error:{Code: Message:}}"]

### What did you see instead?

changefeed status will not change from normal to error，and checkpoint tso still Increase

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
6.1.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
6.1.0
```

TiCDC version (execute `cdc version`):

```console
6.1.0
```

**Comment by hi-rustin** [comment] 2022-08-24 10:47
I can't reproduce this issue on aws.
1. create an msk cluster on aws
2. create a tidb cluster on ec2
3. create changefeed
4. start the sysbench to write data
5. check the changefeed state is normal
6. delete the msk cluster 
7. check if the changefeed state is an error and the checkpoint will not move forward
```log
[
  {
    "id": "06f8938b-ace7-4b23-a627-c709ecc05961",
    "namespace": "default",
    "summary": {
      "state": "error",
      "tso": 435509686729965570,
      "checkpoint": "2022-08-24 10:40:11.122",
      "error": {
        "addr": "127.0.0.1:8300",
        "code": "CDC:ErrKafkaNewSaramaProducer",
        "message": "[CDC:ErrKafkaNewSaramaProducer]new sarama producer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
      }
    }
  }
]
```

**Comment by hi-rustin** [comment] 2022-08-24 12:03
I see what happens.

This issue is because we have no workload when we delete the MSK cluster.

If you add a workload for the upstream then it will be an error as soon as possible.

**Comment by hi-rustin** [comment] 2022-08-25 03:24
There is no correctness issue. So I am going to close it.

**Closed by hi-rustin** 2022-08-25 03:24 UTC
Labels: type/bug, area/ticdc
