### ISSUE TITLE
TiCDC admin job blocked, and etcd worker may be stuck

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#4211] opened 2022-01-04 07:35 UTC
### What did you do?

```
tiup cluster deploy lingjin-kafka-cluster-test v5.5.0-nightly-20220104 kafka-cluster-testing.yaml -p -u root

tiup ctl:v5.5.0-nightly-20220104 cdc changefeed create --pd=http://172.16.7.51:2379 --sink-uri="kafka://172.16.6.111:9092/normal-incremental-test?protocol=open-protocol"

tiup ctl:v5.5.0-nightly-20220104 cdc changefeed pause --pd=http://172.16.7.51:2379 --changefeed-id="bbadf644-73eb-4d07-a8f3-1f245f82b9a9"
```

### What did you expect to see?

changefeed's state become `stopped`

### What did you see instead?

it is still normal.

blocked for a few minutes, and then become `stopped`.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Git Hash: 

```console
fc70dbde8
```

**Comment by 3AceShowHand** [comment] 2022-01-04 07:35
[cdc.log](https://github.com/pingcap/tiflow/files/7806030/cdc.log)

**Comment by 3AceShowHand** [comment] 2022-01-04 07:39
it looks that the `admin` job was handled, but it was stucked when try to update the etcd.

**Comment by asddongmen** [comment] 2022-01-04 07:42
```log
[2022/01/04 15:18:56.439 +08:00] [WARN] [client.go:226] ["etcd client outCh blocking too long, the etcdWorker may be stuck"] [duration=3m55.999651547s]
[2022/01/04 15:18:56.992 +08:00] [WARN] [etcd_worker.go:242] ["EtcdWorker reactor tick took too long"] [duration=4m5.165662023s]
```
It seems that the owner is stucked.

**Comment by 3AceShowHand** [comment] 2022-01-04 08:05
[Uploading cdc-126.log…]()

**Comment by 3AceShowHand** [comment] 2022-01-04 08:05
kafka `min.insync.replicas` is set to `2`, and `replication-factor` is `1`

**Comment by 3AceShowHand** [comment] 2022-01-04 08:22
[Uploading server.log…]()

**Comment by 3AceShowHand** [comment] 2022-01-04 08:23
[server.log](https://github.com/pingcap/tiflow/files/7806279/server.log)

**Comment by 3AceShowHand** [comment] 2022-01-04 08:23
[cdc-126.log](https://github.com/pingcap/tiflow/files/7806280/cdc-126.log)

**Comment by hi-rustin** [comment] 2022-01-10 07:11
Duplicate of #4241

**Closed by hi-rustin** 2022-01-10 07:11 UTC
Labels: type/bug, severity/moderate, type/enhancement, area/ticdc
