### ISSUE TITLE
changefeed checkpoint and resolved ts stucks after scaling cdc 

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#9500] opened 2023-08-04 05:04 UTC
### What did you do?

0. TiDB cluster with GC disabled
1. get TS1: tso: 443311646330585102, time: 2023-08-03 21:55:25.077000
2. run lightning tidb backend to import some data to tidb cluster
3. get TS2: tso: 443312405224357894, time: 2023-08-03 22:43:40.027000
4. Cluster with 1 TiCDC, create changefeed (enable-table-across-nodes = true) with start-ts=TS1, and wait changefeed advance to TS2, remove changefeed
5. Scale TiCDC from 1 to 2, create changefeed  (enable-table-across-nodes = true) with start-ts=TS1, and wait changefeed advance to TS2, remove changefeed
6. Scale TiCDC from 2 to 3, create changefeed  (enable-table-across-nodes = true) with start-ts=TS1, and wait changefeed advance to TS2, remove changefeed
7. Scale TiCDC from 3 to 4, create changefeed  (enable-table-across-nodes = true) with start-ts=TS1, and wait changefeed advance to TS2, remove changefeed

### What did you expect to see?

changefeed should always work normally after CDC scale and re-creating the changefeed.

### What did you see instead?

After scale TiCDC from 3 to 4, CDC changefeed and resolved ts stucks.

![image](https://github.com/pingcap/tiflow/assets/7403864/b600b816-693d-4877-9739-0729b029f17f)
![image](https://github.com/pingcap/tiflow/assets/7403864/952a2b97-627c-4fce-8310-6e6c875a28a4)

### Versions of the cluster

[2023/08/03 21:54:27.159 +00:00] [INFO] [version.go:47] ["Welcome to Change Data Capture (CDC)"] [release-version=v7.3.0] [git
-hash=22d39ad53bc316c93a965449f8ad0e979e3c1471] [git-branch=heads/refs/tags/v7.3.0] [utc-build-time="2023-08-03 10:07:47"] [go-version="go version go1.20.7 linux/amd64"] [failpoint-build=false]

**Comment by asddongmen** [comment] 2023-08-04 07:55
Conclusion: Release blocking is not necessary.

Root cause: Not yet identified.

Current investigation:

- The table sink in ticdc-0 did not start, resulting in no data being sent downstream by ticdc-0.
- This may be caused by the sorter not advancing resolvedTs or the owner not receiving the table state change message sent by the processor.

Further action:

- Attempt to reproduce the issue.
- Add more log statements in the related code block to aid in investigating.

@fubinzh

**Comment by fubinzh** [comment] 2023-08-04 07:57
@asddongmen Is there any work around if it happened?

**Comment by asddongmen** [comment] 2023-10-31 08:26
> @asddongmen Is there any work around if it happened?

pause + resume the changefeed

**Comment by asddongmen** [comment] 2024-01-20 01:50
This issue seems a duplicate of #10157. 
If it happens again, feel free to reopen it and contact me.

**Closed by asddongmen** 2024-01-20 01:50 UTC
Labels: type/bug, severity/major, area/ticdc, affects-7.1, affects-7.3, affects-7.5
