### ISSUE TITLE
Owner exited: [error="rpc error: code = Unknown desc = OK: HTTP status code 200; transport: missing content-type field

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#2693] opened 2021-08-31 08:14 UTC
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- 8 cdc nodes, 1 changefeed, 6w+ tables.
- Workload is DML + DDL(create table)
- Restart all pd: kubectl delete pod db-pd-0 db-pd-1 db-pd-2 ...

2. What did you expect to see?

- Only owner capture exited with error:  pd connection error,  [PD:client:ErrClientGetTSO]

3. What did you see instead?

- 2 Captures exited. 

> one capture log: 

  ![image](https://user-images.githubusercontent.com/78345569/131467209-2da38629-b282-4516-94a3-eed0309f74f3.png)

> The other owner capture log:

   ![image](https://user-images.githubusercontent.com/78345569/131467272-c6c7a79a-ef2d-4f55-ab5c-16d6390990ef.png)

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        4.0.14
        ```

    - TiCDC version (execute `cdc version`):

        ```
        4.0.14 cloud        
        ```

**Comment by liuzix** [comment] 2021-09-02 15:10
I suspect this problem is related to #2708 caused by PD (Etcd) unavailability. These two issues should be investigated together, and PD metrics should be taken into account.

**Comment by overvenus** [comment] 2022-01-25 12:20
We have confirmed this issue is fixed in release-5.4.

**Closed by overvenus** 2022-01-25 12:20 UTC
Labels: type/bug, priority/p1, severity/major, area/ticdc
