### ISSUE TITLE
redo log changefeed enter failed state when resuming changefeed and injecting s3 network partition at the same time

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#10331] opened 2023-12-19 12:17 UTC
### What did you do?

1. Create cdc changefeed with redo log on
2. Run workload
3. Pause changefeed
4. Inject S3 partition for 10s and at the same time resume cdc changefeed.

### What did you expect to see?

changefeed should tolerate s3 partition of 10s

### What did you see instead?

CDC changefeed entered failed state.

![image](https://github.com/pingcap/tiflow/assets/7403864/6b1b1ee3-de3f-4800-b399-98ec68870e3d)

### Versions of the cluster

bash-5.1# /cdc version
Release Version: v6.5.6-20231218-bfece83
Git Commit Hash: bfece839d3285760e6b8c3b2728004b525d819db
Git Branch: heads/refs/tags/v6.5.6-20231218-bfece83
UTC Build Time: 2023-12-18 14:02:02
Go Version: go version go1.19.13 linux/amd64
Failpoint Build: false

**Comment by sdojjy** [comment] 2023-12-19 13:50
Changefeed will check if the redo storage is available, if not  CDC will set changefeed to failed status. This behavior has been changed since v7.1. Close this issue as it can not reproduce on the latest version.

**Closed by sdojjy** 2023-12-19 13:50 UTC
Labels: type/bug, severity/major, area/ticdc, may-affects-5.4, may-affects-6.1, may-affects-6.5
