### ISSUE TITLE
Many DDL lost

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#4782] opened 2022-03-04 16:11 UTC
### What did you do?

360 workload, just sync data, no any chaos.
cdc log:
   [2022/03/04 10:09:21.468 +00:00] [INFO] [client.go:800] ["start new request"] [changefeed=qihoo360-sync-task] [request="{\"header\":{\"cluster_id\":7071145442550887748,\"ticdc_version\":\"5.5.0-nightly\
[2022/03/04 10:09:22.889 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_3 DROP PARTITION p20210508;"] [job="ID:267, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.889 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_3 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:269, T
[2022/03/04 10:09:22.889 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_5 DROP PARTITION p20210508;"] [job="ID:270, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.889 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_5 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:272, T
[2022/03/04 10:09:22.890 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_7 DROP PARTITION p20210508;"] [job="ID:273, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.890 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_7 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:275, T
[2022/03/04 10:09:22.890 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_8 DROP PARTITION p20210508;"] [job="ID:276, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.890 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_8 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:278, T
[2022/03/04 10:09:22.890 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_9 DROP PARTITION p20210508;"] [job="ID:279, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.891 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_9 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:281, T
[2022/03/04 10:09:22.891 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_0 DROP PARTITION p20210508;"] [job="ID:282, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.891 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_0 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:284, T
[2022/03/04 10:09:22.891 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_1 DROP PARTITION p20210508;"] [job="ID:285, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.892 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_1 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:287, T
[2022/03/04 10:09:22.892 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_2 DROP PARTITION p20210508;"] [job="ID:288, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.892 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_2 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:290, T
[2022/03/04 10:09:22.892 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_4 DROP PARTITION p20210508;"] [job="ID:291, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.893 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_4 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:293, T
[2022/03/04 10:09:22.893 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_6 DROP PARTITION p20210508;"] [job="ID:294, Type:drop partition, State:done, SchemaSt
[2022/03/04 10:09:22.893 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="ALTER TABLE workload.oncall2929_6 ADD PARTITION (PARTITION p20210515 VALUES LESS THAN ('20210516'))"] [job="ID:296, T
[2022/03/04 10:09:22.893 +00:00] [INFO] [schema_storage.go:572] ["handle DDL"] [DDL="CREATE TABLE IF NOT EXISTS finishmark (foo BIGINT PRIMARY KEY)"] [job="ID:298, Type:create table, State:done, SchemaS
[2022/03/04 10:09:23.889 +00:00] [INFO] [statistics.go:151] ["sink replication status"] [name=mysql] [changefeed=qihoo360-sync-task] [capture=upstream-ticdc-0.upstream-ticdc-peer.cdc-testbed-tps-605479-
[2022/03/04 10:14:13.776 +00:00] [INFO] [region_worker.go:242] ["single region event feed disconnected"]

### What did you see instead?

table finishmark lost, partition different between upstream tidb and downstream mysql.
![image](https://user-images.githubusercontent.com/78345569/156799169-b4b7b4ca-f013-4398-9e19-9a8c3cd9674e.png)

![image](https://user-images.githubusercontent.com/78345569/156799024-cc92c4a5-15a4-4aac-9847-6aa1610dba04.png)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
Release Version: v5.5.0-nightly
Edition: Community
Git Commit Hash: 74d74b0a7b6bee275d392199bb319859682627ff
Git Branch: heads/refs/tags/v5.5.0-nightly
UTC Build Time: 2022-03-04 06:12:57
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
TiKV 
Release Version:   6.0.0-alpha
Edition:           Community
Git Commit Hash:   18a119cbc551db53c1025912c164d994461f3aee
Git Commit Branch: heads/refs/tags/v5.5.0-nightly
UTC Build Time:    2022-03-04 06:09:32
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   jemalloc mem-profiling portable sse test-engines-rocksdb cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
Release Version: v5.5.0-nightly
Git Commit Hash: f113d36bf192460eed0a0b8a96376690fce69902
Git Branch: heads/refs/tags/v5.5.0-nightly
UTC Build Time: 2022-03-04 06:08:36
Go Version: go version go1.16.4 linux/amd64
Failpoint Build: false
```

**Comment by 3AceShowHand** [comment] 2022-03-09 04:26
investigate all PR between `2.21 ~ 3.4`

**Comment by overvenus** [comment] 2022-03-25 09:52
It should be fixed by https://github.com/tikv/tikv/pull/12262, let's keep it open and wait another round testing.

**Comment by overvenus** [comment] 2022-03-31 03:18
Can't reproduce again.

**Closed by overvenus** 2022-03-31 03:18 UTC
Labels: type/bug, severity/critical, found/automation, area/ticdc, may-affects-4.0, may-affects-5.1, may-affects-5.2, may-affects-5.3, may-affects-5.4, may-affects-5.0
