### ISSUE TITLE
changefeed lag get more and more after inject pd leader io delay 10ms even if fault recover

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#10800] opened 2024-03-18 03:33 UTC
### What did you do?

1、create changefeed with mysql sink （downstream is tidb cluster）
    changefeedOptions:
    -   changefeed_id: ticdc-task   
        config: "memory-quota = 2147483648\n[consistent]\nlevel = \"eventual\"\nflush-interval = 500\nstorage = \"s3://tmp/test-changefeed?access-key=xxx&secret-access-key=xxx&endpoint=http%3a%2f%2fminio-peer%3a9000\""  
2、run sysbench
subType:"oltp_read_write"
tableNum:64
tableSize:70000000
3、inject pd leader io delay 10ms
![image](https://github.com/pingcap/tiflow/assets/84712107/00af851b-9be2-407c-a95f-cda98a6ebee6)

### What did you expect to see?

changefeed lag can recover after fault recover

### What did you see instead?

changefeed lag get more and more after inject pd leader io delay 10ms even if fault revoer

![img_v3_0293_c1370fbb-430e-4718-ac5e-9884690ae65g](https://github.com/pingcap/tiflow/assets/84712107/1dd7d4df-eeb1-4e25-bda7-b56d8573b272)

### Versions of the cluster

./cdc version
 Release Version: v8.0.0-alpha
Git Commit Hash: 0cbec45b32532b2e8e101eda4edd7e6ea5bfeca1
Git Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time: 2024-03-17 12:07:57
Go Version: go version go1.21.6 linux/amd64
Failpoint Build: false

**Comment by asddongmen** [comment] 2024-03-19 02:24
After investigation, it has been confirmed that the issue is due to https://github.com/pingcap/tidb/issues/51871.
When I downgrade the downstream TiDB of TiCDC to v7.5.0, the lag disappears.

**Comment by asddongmen** [comment] 2024-03-19 02:29
Should close it after TiDB fix https://github.com/pingcap/tidb/issues/51871 and retest.

**Comment by asddongmen** [comment] 2024-04-03 02:10
Fixed by https://github.com/pingcap/tidb/pull/51911

**Closed by asddongmen** 2024-04-03 02:10 UTC
Labels: type/bug, severity/critical, area/ticdc, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5, affects-8.0
