### ISSUE TITLE
ticdc: kafka CI failed at `default_value`, ticdc v7.5

### ISSUE THREAD

**Issue by wlwilliamx** [pingcap/tiflow#11893] opened 2024-12-17 07:43 UTC
### What did you do?

PR #11887 CI failed, https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Frelease-7.5%2Fpull_cdc_integration_kafka_test/detail/pull_cdc_integration_kafka_test/985/pipeline

### What did you see instead?

CI log.
```
[2024/12/17 15:13:16.589 +08:00] [WARN] [utils.go:532] ["target lack data"] [row="{ id2: 730000029, v0: 11, v1: e0,e1, id1: 730000028,  }"]

[2024/12/17 15:13:16.589 +08:00] [DEBUG] [diff.go:700] ["[insert]"] [sql="REPLACE INTO `test`.`testMultiDDLs2df8823d_2527_45b9_b492_21743cd171d7`(`id1`,`id2`,`v0`,`v1`) VALUES (730000028,730000029,11,'e0,e1');"]

[2024/12/17 15:13:16.591 +08:00] [DEBUG] [diff.go:263] ["all consume tasks finished"]

[2024/12/17 15:13:16.591 +08:00] [DEBUG] [diff.go:762] ["insert node"] ["chunk index"="{\"table-index\":31,\"bucket-index-left\":0,\"bucket-index-right\":506,\"chunk-index\":0,\"chunk-count\":1}"]

[2024/12/17 15:13:16.591 +08:00] [INFO] [diff.go:732] ["write sql channel closed"]

[2024/12/17 15:13:16.591 +08:00] [INFO] [diff.go:723] ["close writeSQLs goroutine"]

[2024/12/17 15:13:16.591 +08:00] [INFO] [diff.go:405] ["Stop do checkpoint"]

[2024/12/17 15:13:16.591 +08:00] [INFO] [checkpoints.go:225] ["save checkpoint"] [chunk="{\"state\":\"success\",\"chunk-range\":{\"index\":{\"table-index\":38,\"bucket-index-left\":0,\"bucket-index-right\":234,\"chunk-index\":0,\"chunk-count\":1},\"type\":1,\"bounds\":[],\"is-first\":false,\"is-last\":false,\"where\":\"((TRUE) AND (TRUE))\",\"args\":null},\"index-id\":1}"] [state=success]

[2024/12/17 15:13:16.591 +08:00] [INFO] [diff.go:379] ["close handleCheckpoint goroutine"]

[2024/12/17 15:13:16.774 +08:00] [INFO] [main.go:114] ["check data finished"] [cost=900.915992ms]

[2024/12/17 15:13:16.774 +08:00] [WARN] [main.go:105] ["check failed!!!"]
```

### Versions of the cluster

TiCDC version (execute `cdc version`):

```console
[release-version=v7.5.4-17-ga29d5121e] [git-hash=a29d5121eed98638e5346266a62ecc8f16505a69] [git-branch=HEAD] [utc-build-time="2024-12-17 01:51:35"] [go-version="go version go1.21.10 linux/amd64"]
```

**Comment by 3AceShowHand** [comment] 2024-12-20 07:21
This may caused by the tikv issue https://github.com/tikv/tikv/pull/18017, cannot be reproduced after it fixed, so close this

**Closed by 3AceShowHand** 2024-12-20 07:21 UTC
Labels: type/bug, area/ticdc
