### ISSUE TITLE
When the CDC cannot connect downstream, the changefeed status is not set to error

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tiflow#4915] opened 2022-03-16 07:42 UTC
### What did you do?

1. create vpc peering between kafka/mysql and tidb in dbaas
2. create cdc changefeed between tidb and kafka/mysql
3. delete vpc peering

### What did you expect to see?

1. When the CDC cannot connect downstream, the changefeed status should be set to error

### What did you see instead?

the changefeed status is not set to error

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by 3AceShowHand** [comment] 2022-03-16 12:23
can you provide more details, such as logs.

**Comment by zhaoxinyu** [comment] 2022-03-18 09:08
@zhongmin-amin, could you provide the corresponding logs?

**Comment by 3AceShowHand** [comment] 2022-03-18 10:19
The root cause is that when the downstream MySQL is unavailable, changefeed would spend too much time trying to execute the DDL.

At the moment, this would retry 20 times at the most, and each time cost 2m as write timeout

**Comment by 3AceShowHand** [comment] 2022-03-21 07:12
At the moment, MySQL Sink dispatch DML / DDL have the following behavior:

* DML: retry = 8, read / write / dial = 2m
* DDL: retry = 20, read / write / dial = 2m

Consider that downstream MySQL crashed, MySQL sink would retry a long time then report errors to the owner.

For DDL, it would be quite time-consuming, the `write timeout` 2m is not long enough. User may expect that they can control such configurations.

**Comment by 3AceShowHand** [comment] 2022-03-24 06:38
For long time-consuming DDL, it would be useless to make DDL timeout larger than 2m, even user can configure the DDL timeout, there is still a chance that DDL execution would cost a long time. TiCDC would support DDL filter functionality in the future, which would allow specific DDL to be ignored by the TiCDC, such as `Add Index` / `Add Column` etc, in such a  way, the whole changefeed won't be blocked by the DDL's execution, and user can execute DDL manually in the downstream if necessary.

Conclusion: we do not think it's a must to support MySQL sink timeout configuration, because this won't solve the root problem.

**Comment by 3AceShowHand** [comment] 2022-03-24 06:43
closed by the comment above.

**Comment by SunRunAway** [comment] 2022-03-29 09:34
@3AceShowHand 

The title describes that "the changefeed status is not set to error". Please make sure that the status is **error** when downstream MySQL is unavailable.


From https://docs.pingcap.com/tidb/stable/manage-ticdc
> Error: The replication task returns an error. The replication cannot continue due to some recoverable errors. The changefeed in this state keeps trying to resume until the state transfers to Normal. The changefeed in this state blocks GC operations.

**Comment by SunRunAway** [comment] 2022-03-29 09:41
1. status of changfeed should be error when it stops replicating data.
2. The status should be **error** for the duration of when retrying until it can resume syncing
3. After retrying more than 20 times. The status should become to **FAILED**

**Comment by leoppro** [comment] 2022-03-29 11:30
![IbHXInxWoH](https://user-images.githubusercontent.com/33834665/160601402-0c33c21f-88b8-495f-bccb-3b5c0663ffd1.png)

here we can add a `retrying` status.
`error` to `retrying`: ticdc start to retry and try start changefeed again.
`retrying` to `normal`: changefeed is already started and checkpoint ts is pushed.

**Comment by overvenus** [comment] 2022-03-30 01:09
I don't think we need a new state, we can rename 'error' to 'unhealthy' and provide extra retry information in changefeed API.

For the issue, I think the default setting about retry count and timeout is too large. We can set a smaller timeout and let mysql report fast. e.g., "mysql://${MySQLADDR}/?timeout=s0s"

**Comment by leoppro** [comment] 2022-07-04 03:50
> I don't think we need a new state, we can rename 'error' to 'unhealthy' and provide extra retry information in changefeed API.
> 
> For the issue, I think the default setting about retry count and timeout is too large. We can set a smaller timeout and let mysql report fast. e.g., "mysql://${MySQLADDR}/?timeout=20s"

Ok,fine. we won't add `retrying` state. And `error` is OK, no need to change the name. There are two issues that need to be solved:
* only if the error is retry and resolved, the state can be switched to normal. but the state will be switched to normal when starting to retry for now.
* provide extra retry information in changefeed API

**Comment by asddongmen** [comment] 2022-07-16 09:39
I will do this job in next week.

**Comment by asddongmen** [comment] 2023-06-01 05:21
Now, we add some error message to indicate some error happen in the changefeed.

**Closed by asddongmen** 2023-06-01 05:21 UTC
Labels: component/sink, type/enhancement, area/ticdc
