### ISSUE TITLE
ticdc: kafka CI failed, target had superfluous data

### ISSUE THREAD

**Issue by wlwilliamx** [pingcap/tiflow#11891] opened 2024-12-17 06:23 UTC
### What did you do?

PR #11887 CI failed. https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Frelease-7.5%2Fpull_cdc_integration_kafka_test/detail/pull_cdc_integration_kafka_test/982/pipeline

### What did you see instead?

tester.log
```
[2024/12/17 11:59:19.835 +08:00] [INFO] [diff.go:247] ["don't have checkpoint info, or the last check success, or config changed, will split chunks"]
[2024/12/17 11:59:19.837 +08:00] [INFO] [chunk.go:239] ["split range by random"] [rowCount=951] [splitChunkNum=1]
[2024/12/17 11:59:19.839 +08:00] [INFO] [checkpoint.go:154] ["initial chunks"] [cost=2.151899ms]
[2024/12/17 11:59:19.845 +08:00] [WARN] [diff.go:556] ["checksum is not equal"] [table=`test`.`ptest`] [where="((TRUE) AND TRUE)"] [sourceChecksum=1896612151] [targetChecksum=2813330171] [getSourceChecksumCost=2.535373ms] [getTargetChecksumCost=2.568256ms]
[2024/12/17 11:59:19.845 +08:00] [INFO] [diff.go:467] ["select data and then check data"] [table=`test`.`ptest`] [where="((TRUE) AND TRUE)"]
[2024/12/17 11:59:19.858 +08:00] [WARN] [diff.go:925] ["target had superfluous data"] [row="{ a: 526, b: -1433076081, nIggh: XLwD0KkUVwDHgl7ApA, d: 12:04:22,  }"]
[2024/12/17 11:59:19.858 +08:00] [INFO] [diff.go:737] ["[delete]"] [sql="DELETE FROM `test`.`ptest` WHERE `a` = 526 AND `b` = -1433076081 AND `nIggh` = 'XLwD0KkUVwDHgl7ApA' AND `d` = '12:04:22';"]
[2024/12/17 11:59:19.923 +08:00] [INFO] [db.go:111] ["check equal"] [sql="DELETE FROM `test`.`ptest` WHERE `a` = 526 AND `b` = -1433076081 AND `nIggh` = 'XLwD0KkUVwDHgl7ApA' AND `d` = '12:04:22';\n"]
[2024/12/17 11:59:19.923 +08:00] [WARN] [diff.go:925] ["target had superfluous data"] [row="{ b: -1909487476, nIggh: aiFKPGw5ilsueDjPb2lmziepvoIs3YRlEJrsmowiJu8, d: 12:07:35, a: 713,  }"]
[2024/12/17 11:59:19.923 +08:00] [INFO] [diff.go:737] ["[delete]"] [sql="DELETE FROM `test`.`ptest` WHERE `a` = 713 AND `b` = -1909487476 AND `nIggh` = 'aiFKPGw5ilsueDjPb2lmziepvoIs3YRlEJrsmowiJu8' AND `d` = '12:07:35';"]
[2024/12/17 11:59:20.023 +08:00] [INFO] [db.go:111] ["check equal"] [sql="DELETE FROM `test`.`ptest` WHERE `a` = 713 AND `b` = -1909487476 AND `nIggh` = 'aiFKPGw5ilsueDjPb2lmziepvoIs3YRlEJrsmowiJu8' AND `d` = '12:07:35';\n"]
[2024/12/17 11:59:20.024 +08:00] [WARN] [diff.go:765] ["rows is not equal"] [table=`test`.`ptest`] [where="((TRUE) AND TRUE)"] [cost=179.29533ms]
[2024/12/17 11:59:20.028 +08:00] [WARN] [diff.go:383] ["check chunk data not equal"] [chunk="{\"id\":0,\"bounds\":[],\"where\":\"((TRUE) AND TRUE)\",\"args\":null,\"state\":\"failed\"}"]
[2024/12/17 11:59:20.124 +08:00] [INFO] [checkpoint.go:216] ["summary info"] [instanceID=] [schema=test] [table=ptest] [chunkNum=1] [successNum=0] [failedNum=1] [ignoreNum=0]
[2024/12/17 11:59:20.127 +08:00] [FATAL] [db.go:385] ["sourceDB don't equal targetDB"] [stack="github.com/pingcap/tiflow/tests/integration_tests/cdc/dailytest.RunTest\n\t/home/jenkins/agent/workspace/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test/tiflow/tests/integration_tests/cdc/dailytest/db.go:385\ngithub.com/pingcap/tiflow/tests/integration_tests/cdc/dailytest.Run\n\t/home/jenkins/agent/workspace/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test/tiflow/tests/integration_tests/cdc/dailytest/dailytest.go:53\nmain.main\n\t/home/jenkins/agent/workspace/pingcap/tiflow/release-7.5/pull_cdc_integration_kafka_test/tiflow/tests/integration_tests/cdc/cdc.go:70\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267"]
exit status 1
```

### Versions of the cluster

TiCDC version (execute `cdc version`):
```console
[release-version=v7.5.4-17-ga29d5121e] [git-hash=a29d5121eed98638e5346266a62ecc8f16505a69] [git-branch=HEAD]
```

**Comment by 3AceShowHand** [comment] 2024-12-20 07:21
This may caused by the tikv issue https://github.com/tikv/tikv/pull/18017, cannot be reproduced after it fixed, so close this

**Closed by 3AceShowHand** 2024-12-20 07:21 UTC
Labels: type/bug, area/ticdc
