### ISSUE TITLE
checkpoint lag is increasing while sink rows decreasing a lot

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tiflow#5460] opened 2022-05-18 07:02 UTC
### What did you do?

- 3 cdc node, 1 changefeed, kafka sink
- workload: sysbench oltp_write_only 16 thread, 16 tables, prepare and run

### What did you see instead?

- 
![hmBMCtNWq7](https://user-images.githubusercontent.com/78345569/168975717-9e4c0c5e-74c8-4a3e-b695-7e2a524f464f.jpg)

![LcXkK1oNQ4](https://user-images.githubusercontent.com/78345569/168975664-540b799e-f53b-4af6-9642-7f806a41d0d0.jpg)

- 
![NwHgKdjYUJ](https://user-images.githubusercontent.com/78345569/168975747-03edb554-7407-4fde-89b8-4795dfc0709a.jpg)
![NexvNIiTWI](https://user-images.githubusercontent.com/78345569/168975763-646146d7-ca45-454e-aabe-e684bdf65100.jpg)

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

**Comment by hi-rustin** [comment] 2022-05-18 07:24
Duplicate of https://github.com/pingcap/tiflow/issues/5459

**Closed by hi-rustin** 2022-05-18 07:24 UTC
Labels: type/bug, area/ticdc
