### ISSUE TITLE
Server creates pd client failed

### ISSUE THREAD

**Issue by buchuitoudegou** [pingcap/tiflow#4825] opened 2022-03-09 08:39 UTC
### What did you do?

1. deploy TiDB cluster with PD:
```shell
bin/pd-server --name="pd" \
         --data-dir="pd" \
	--name="pd1" \
        --client-urls="http://0.0.0.0:2379" \
        --peer-urls="http://0.0.0.0:2380" \
	--advertise-client-urls="http://$myipv4:2379" \
	--advertise-peer-urls="http://$myipv4:2380" \
	--initial-cluster="pd1=http://$myipv4:2380"
```

2. run ticdc by cmd:
```shell
./bin/cdc server \
	--pd=http://${myipv4}:2379 \
	--log-file=ticdc_1.log \
	--addr=0.0.0.0:8301 \
	--advertise-addr=127.0.0.1:8301 \
	--data-dir=/tmp/cdc
```
3. create replication task
```shell
bin/cdc cli changefeed create --pd=http://${myipv4}:2379 \
--sink-uri="mysql://root:123456@127.0.0.1:3306/" \
--changefeed-id="test-topsql" \
--sort-engine="unified"
```

### What did you expect to see?

create task successfully

### What did you see instead?

CDC server error:
```
Error: run server: [CDC:ErrServerNewPDClient]server creates pd client failed: [pd] failed to get cluster id
```
task creating error:
```
[2022/03/09 16:32:39.890 +08:00] [WARN] [cli_changefeed_list.go:102] ["query changefeed info failed"] [error="[CDC:ErrOwnerNotFound]owner not found"]
```

### Versions of the cluster

latest master branch of pd, TiDB, TiKV, and TiCDC

**Comment by buchuitoudegou** [comment] 2022-03-09 08:39
I believed I've successfully run these commands yesterday before I updated my local repo😭

**Comment by sdojjy** [comment] 2022-09-07 06:27
Not able to reproduce in the test case, close it now. Reopen it If can reproduce it one day.

**Closed by sdojjy** 2022-09-07 06:27 UTC
Labels: type/bug, severity/moderate, area/ticdc
