### ISSUE TITLE
TiCDC changefeed's resolved-ts is stuck

### ISSUE THREAD

**Issue by sdojjy** [pingcap/tiflow#10157] opened 2023-11-24 09:21 UTC
<img width="1441" alt="image" src="https://github.com/pingcap/tiflow/assets/1779704/15daecf6-b958-48e1-bf36-315a293bc02e">

the workaround is pause/resume changefeed

**Comment by asddongmen** [comment] 2023-12-19 03:17
This issue has occurred a couple of times recently. 
It always happens when a cross-table region merging operation finishes in the upstream TiKV. Logs like the ones below were spotted in the environment where this issue occurred:
```
cdc log:
[2023/12/14 07:44:47.156 +08:00] [INFO] [region_cache.go:1070] ["switch region peer to next due to send request fail"] [current="region ID: 41899, meta: id:41899 start_key:\"t\\200\\000\\000\\000\\000\\000\\002\\377K_i\\200\\000\\000\\000\\000\\377\\000\\000\\003\\003\\200\\000\\001\\214\\377]\\r\\035\\036\\0014f2\\377bc965\\377-8\\37797d-4e\\377c\\3773-86b4-\\377\\377da33ab63\\377\\3778c94\\000\\000\\000\\377\\000\\373\\000\\000\\000\\000\\000\\000\\371\" end_key:\"t\\200\\000\\000\\000\\000\\000\\002\\377K_r\\001debb\\3777402\\377-87\\37769-40\\37744\\377-b0c6-\\3778\\3778a6e01d\\377\\377aea6\\000\\000\\000\\000\\377\\373\\000\\000\\000\\000\\000\\000\\000\\370\" region_epoch:<conf_ver:5 version:2150 > peers:<id:41900 store_id:1 > peers:<id:41901 store_id:3 > peers:<id:41902 store_id:2 > , peer: id:41900 store_id:1 , addr: 0.0.0.17:20160, idx: 0, reqStoreType: TiKvOnly, runStoreType: tikv"] [needReload=false] [error="[CDC:ErrEventFeedAborted]single event feed aborted"]
[2023/12/14 07:45:16.448 +08:00] [INFO] [replication_manager.go:583] ["schedulerv3: slow table"] [namespace=default] [changefeed=x] [tableID=587] [tableStatus=] [checkpointTs=446303066237960202] [resolvedTs=446303066237960202] [checkpointLag=30.005267224s]

pd log:
[2023/12/14 07:44:41.685 +08:00] [INFO] [operator_controller.go:443] ["add operator"] [region-id=43867] [operator="\"merge-region {merge: region 43867 to 41899} (kind:merge, region:43867(2148, 5), createAt:2023-12-14 07:44:41.685181802 +0800 CST m=+9289232.097638819, startAt:0001-01-01 00:00:00 +0000 UTC, currentStep:0, size:1, steps:[merge region 43867 into region 41899]锛宼imeout:[10m0s])\""] [additional-info=]

[2023/12/14 07:44:47.144 +08:00] [INFO] [region.go:631] ["region Version changed"] [region-id=41899] [detail="StartKey Changed:{7480000000000002FF4B5F720130613335FF38383732FF2D3339FF34332D3432FF3562FF2D396139332DFF30FF37663538393034FFFF3063383300000000FFFB00000000000000F8} -> {7480000000000002FF4B5F698000000000FF000003038000018CFF5D0D1D1E01346632FF6263393635FF2D38FF3937642D3465FF63FF332D383662342DFFFF6461333361623633FFFF38633934000000FF00FB000000000000F9}, EndKey:{7480000000000002FF4B5F720164656262FF37343032FF2D3837FF36392D3430FF3434FF2D623063362DFF38FF38613665303164FFFF6165613600000000FFFB00000000000000F8}"] [old-version=2145] [new-version=2150]


tikv log:
[2023/12/14 07:44:47.157 +08:00] [INFO] [endpoint.rs:1157] ["cdc downstream starts to initialize"] [downstream_id=DownstreamId(1140540)] [region_id=41899]
[2023/12/14 07:44:47.157 +08:00] [ERROR] [endpoint.rs:759] ["cdc initialize fail: Request error message: \"peer is not leader for region 41899, leader may Some(id: 41900 store_id: 1)\" not_leader { region_id: 41899 leader { id: 41900 store_id: 1 } }"] [region_id=41899]
[2023/12/14 07:44:47.157 +08:00] [INFO] [endpoint.rs:513] ["cdc deregister"] [deregister="Deregister { deregister: \"delegate\", region_id: 41899, observe_id: ObserveId(262910), err: Request(message: \"peer is not leader for region 41899, leader may Some(id: 41900 store_id: 1)\" not_leader { region_id: 41899 leader { id: 41900 store_id: 1 } }) }"]
[2023/12/14 07:44:47.157 +08:00] [INFO] [delegate.rs:938] ["stop observing"] [failed=true] [region_id=41899]
[2023/12/14 07:44:47.157 +08:00] [INFO] [delegate.rs:339] ["cdc met region error"] [error="Request(message: \"peer is not leader for region 41899, leader may Some(id: 41900 store_id: 1)\" not_leader { region_id: 41899 leader { id: 41900 store_id: 1 } })"] [region_id=41899]
```

The root cause of this issue is still under investigation.
There are two workarounds of this issue:
- Pause and resume the stuck changefeed.
- Execute `config set enable-cross-table-merge false` to disable the cross-table region merge function in the upstream TiDB.

**Comment by asddongmen** [comment] 2024-01-20 01:20
fixed by #10488

**Closed by asddongmen** 2024-01-20 01:20 UTC
Labels: type/bug, severity/major, area/ticdc, affects-6.1, affects-6.5, affects-7.1, affects-7.5, affects-7.6

**Comment by kennytm** [comment] 2024-07-10 07:37
For quick reference (since this is happening too many times) - this bug has been / will be fixed on:

* v7.5.1
* v7.1.4
* v6.5.8
* v6.1.8

v7.6.0, and also v8.0.0 and above are unaffected.

**Comment by kennytm** [comment] 2025-01-24 08:52
Other than checking for the logs, another potential identification is to look for the dynamics of region split/merge (because it may not manifest with many `region_not_found`/`not_leader` logs). One potential trigger is

1. having a region A with range `[x, z)`, 
2. which is split into region B' = `[x, y)` + region A' = `[y, z)`
3. and later (no time limit), these two regions without further split got reunified into a single region A'' = `[x, z)`

the resolvedTS will then be stuck at the time of merge on the table in the range `[x, z)`.
