### ISSUE TITLE
Unable to enable failpoint on mac

### ISSUE THREAD

**Issue by buchuitoudegou** [pingcap/tiflow#6010] opened 2022-06-23 09:44 UTC
### What did you do?

```
> make failpoint-enable
$(echo $(for p in $(go list ./... | grep -vE 'vendor|proto|tiflow\/tests|integration|testing_utils|pb|pbmock|tiflow\/bin'); do echo ${p#"github.com/pingcap/tiflow/"}|grep -v "github.com/pingcap/tiflow"; done) | xargs tools/bin/failpoint-ctl enable >/dev/null)
case-insensitive import collision: "github.com/pingcap/tiflow/engine/jobmaster/cvsJob" and "github.com/pingcap/tiflow/engine/jobmaster/cvsjob"
```

But I couldn't find "github.com/pingcap/tiflow/engine/jobmaster/cvsJob" in this repo

### Versions of the cluster

ba6ecc27cf55303d3582069f8669ae4de6cf352b

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

**Comment by amyangfei** [comment] 2022-06-24 02:45
Can't reproduce in my environment, `github.com/pingcap/tiflow/engine/jobmaster/cvsJob` has been renamed to `github.com/pingcap/tiflow/engine/jobmaster/cvsjob`, maybe there exists some cache.
Could you please check `git status` or clean go module cache and retry.

**Comment by buchuitoudegou** [comment] 2022-06-24 02:58
> Can't reproduce in my environment, `github.com/pingcap/tiflow/engine/jobmaster/cvsJob` has been renamed to `github.com/pingcap/tiflow/engine/jobmaster/cvsjob`, maybe there exists some cache. Could you please check `git status` or clean go module cache and retry.

Got it. Thx for your advice.

**Comment by maxshuang** [comment] 2022-07-08 06:42
@amyangfei  Please close this issue if you are available.

**Comment by amyangfei** [comment] 2022-07-08 06:53
close now, feel free to reopen it if there is any more question.

**Closed by amyangfei** 2022-07-08 06:53 UTC
Labels: type/bug, area/engine
