### ISSUE TITLE
after restart all tikvs、pds、tidbs，ticdc changefeed can not go on

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tiflow#8316] opened 2023-02-20 10:29 UTC
### What did you do?
1、br restore 20000 warehouse to upstream and tidb downstream
2、create cdc changefeed with config
"replica_config": {
"ignore_ineligible_table": true,
"memory_quota": 2147483648
}
3、run tpcc with 32 threads
4、after restart all tikvs、pds、tidbs

### What did you expect to see?

ticdc changefeed can go on

### What did you see instead?

ticdc changefeed can not go on

### Versions of the cluster

sh-5.1# ./cdc version
Release Version: v6.6.0
Git Commit Hash: https://github.com/pingcap/tiflow/commit/feae75ed4c816da5df52e931cb936a97f619ae0e
Git Branch: heads/refs/tags/v6.6.0
UTC Build Time: 2023-02-15 15:38:00
Go Version: go version go1.19.5 linux/amd64
Failpoint Build: false

**Comment by hi-rustin** [comment] 2023-02-21 09:46
I can not reproduce it on my local machine. Need to wait for the resource and debug when it was reproduced.

**Comment by nongfushanquan** [comment] 2023-09-21 07:34
since this case is already covered by dailyrun test and couldn't reproduce ,so close it . If happen again later , then reopen it  
/close

**Closed by nongfushanquan** 2023-09-21 07:34 UTC
Labels: type/bug, severity/moderate, area/ticdc, may-affects-6.5, may-affects-6.6
