### ISSUE TITLE
redo log changefeed stuck after network chaos injection

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#6859] opened 2022-08-23 09:28 UTC
### What did you do?

1. Start redo log changefeed, store redo log to testing minio server
2. Run sysbench workload for 5 miniutes
3. Run "cdc redo apply" to downstream. (I didn't stop the changefeed before redo apply)
4. Inject network chaos between tikv <-> minio, and cdc <-> minio for 10 minio, then restore the chaos injection.
5. About 2 hours later, I use "cdc cli changefeed list" to check the changefeed status

### What did you expect to see?

Changefeed status should be normal

### What did you see instead?

"cdc cli changefeed list" command stucks.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
| Release Version: v6.2.0-alpha
Edition: Community
Git Commit Hash: 8b5b724d8a932239303a1d0ba547323eb0e5161b
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-08-19 11:28:57
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
```

Upstream TiKV version (execute `tikv-server --version`):

```console
/ # /tikv-server -V
TiKV
Release Version:   6.2.0-alpha
Edition:           Community
Git Commit Hash:   58fa80e0de0d43d473dc456081a4d2b08939e0aa
Git Commit Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time:    2022-08-19 11:03:24
Rust Version:      rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-en
gine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release
```

TiCDC version (execute `cdc version`):

```console
bash-5.1# /cdc version
Release Version: v6.2.0-alpha
Git Commit Hash: 750f0e4ddf97bb4d9feba66799de93113af04405
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-08-22 11:03:29
Go Version: go version go1.18.5 linux/amd64
Failpoint Build: false
```

**Comment by Tammyxia** [comment] 2022-08-24 02:11
Reproduced this issue in  cdc version hotfix 6.1.0 20220817, when test redo storage NFS  umount/mount chaos for 10 hours. I'm not sure if the root cause if exactly the same, but it seems can be debug at the same time.

**Comment by zhaoxinyu** [comment] 2022-08-25 03:01
This issue is called by initializing changfeed for multiple times if network chaos are injected.
The direct reason is `redo.NewManager` failed and `c.initialized` remains false, but ddl_puller and the corresponding goroutines are already created. 
https://github.com/pingcap/tiflow/blob/84a854f6e4ad54a0be131857b0281a3ff6a82ac5/cdc/owner/changefeed.go#L486-L490

 At next tick, ddl_puller and the corresponding goroutines will be created again. Because `c.cancel` will be reassigned with the latest cancel function. It can only cancel the latest created context. The previously created context cannot be cancelled.
https://github.com/pingcap/tiflow/blob/84a854f6e4ad54a0be131857b0281a3ff6a82ac5/cdc/owner/changefeed.go#L466-L467

As a result, `c.releaseResource()` will be blocked at the following line forever. And owner will be blocked forever.
https://github.com/pingcap/tiflow/blob/84a854f6e4ad54a0be131857b0281a3ff6a82ac5/cdc/owner/changefeed.go#L551

**Closed** 2022-08-25 09:56 UTC
Labels: type/bug, severity/major, area/ticdc, affects-5.3, affects-5.2, affects-5.1, affects-5.4, affects-6.0, affects-6.1, affects-6.2
