### ISSUE TITLE
Test ddl_attributes is unstable

### ISSUE THREAD

**Issue by overvenus** [pingcap/tiflow#3180] opened 2021-10-29 05:45 UTC
### Which jobs are flaking?

Test ddl_attributes in #3143 

It fails in CI but pass in manual test.

### Which test(s) are flaking?

* ddl_attributes

### Jenkins logs or GitHub Actions link

[cdc.log.zip](https://github.com/pingcap/ticdc/files/7439144/cdc.log.zip)
[tidb.log.zip](https://github.com/pingcap/ticdc/files/7439145/tidb.log.zip)
[tidb_down.log.zip](https://github.com/pingcap/ticdc/files/7439146/tidb_down.log.zip)

### Anything else we need to know

From TiCDC log, we find FLASHBACK DDL seems fails in upstream TiDB. 

```
[2021/10/28 10:43:36.918 +08:00] [DEBUG] [schema_storage.go:517] ["create table success"] [name=ddl_attributes.attributes_t1] [id=70]
[2021/10/28 10:43:36.922 +08:00] [DEBUG] [schema_storage.go:548] ["handle job: "] ["sql query"="FLASHBACK TABLE attributes_t1 to attributes_t1_back"] [job="ID:72, Type:recover table, State:done, SchemaState:public, SchemaID:57, TableID:59, RowCount:0, ArgLen:0, start time: 2021-10-28 10:43:33.822 +0800 CST, Err:[meta:1146]table doesn't exist, ErrCount:1, SnapshotVersion:0"]
```

**Comment by maxshuang** [comment] 2021-11-01 12:11
@amyangfei @overvenus  In this case,  the  phenomenon that  tidb ddl job has 'done' state and err info  is caused by the retry in tidb. Actually, 'FLASHBACK TABLE attributes_t1 to attributes_t1_back' executed successfully in upstream.

It's ok to use 'done' and 'sync' to mark success ddl job.  Fail ddl job will be marked as 'cancelled' or something else.

**Comment by overvenus** [comment] 2022-03-03 14:54
```log
[2022-03-03T06:51:13.875Z] ERROR 1364 (HY000) at line 8: Field 'id' doesn't have a default value

[2022-03-03T06:51:32.188Z] make: *** [integration_test_mysql] Error 1
```

It fails again. https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/10107/pipeline/#step-470-log-188

**Comment by overvenus** [comment] 2022-03-31 05:29
```
[](https://ci.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/2551/pipeline#step-932-log-321)[](https://ci.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/2551/pipeline#step-932-log-322)[2022-03-30T15:45:03.559Z] table ddl_attributes.finish_mark not exists for 59-th check, retry later

[2022-03-30T15:45:05.543Z] table ddl_attributes.finish_mark not exists for 60-th check, retry later

[2022-03-30T15:45:07.528Z] table ddl_attributes.finish_mark not exists at last check
```

Another failed case, triggered by upstream TiDB CI https://ci.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/2551/pipeline

**Comment by hi-rustin** [comment] 2022-05-13 05:27
Close it because it looks like it hasn't happened again for a long time.

**Closed by hi-rustin** 2022-05-13 05:27 UTC
Labels: component/test, area/ticdc
