### ISSUE TITLE
v5.2.3 upgrade to v5.4.0-nightly-20211221 fail for "server_config is only supported with TiCDC version v4.0.13 or later"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tiflow#4149] opened 2021-12-30 01:50 UTC
### What did you do?

1. install v5.2.3 tidb cluster, with config:
  cdc:
    sorter.max-memory-consumption: 1073741824
2. upgrade to v5.4.0-nightly-20211221
3. upgrade fail 

### What did you expect to see?

upgrade success

### What did you see instead?

2021-12-30T09:17:51.941+0800    INFO    Execute command finished        {"code": 1, "error": "init config failed: cdc-peer:8300: server_config is only supported with TiCDC version v4.0.13 or later", "errorVerbose": "server_config is only supported with TiCDC version v4.0.13 or later\ngithub.com/pingcap/tiup/pkg/cluster/spec.(*CDCInstance).InitConfig\n\tgithub.com/pingcap/tiup/pkg/cluster/spec/cdc.go:168\ngithub.com/pingcap/tiup/pkg/cluster/task.(*InitConfig).Execute\n\tgithub.com/pingcap/tiup/pkg/cluster/task/init_config.go:51\ngithub.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:85\ngithub.com/pingcap/tiup/pkg/cluster/task.(*Parallel).Execute.func1\n\tgithub.com/pingcap/tiup/pkg/cluster/task/task.go:142\nruntime.goexit\n\truntime/asm_amd64.s:1581\ninit config failed: cdc-peer:8300"}

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

TiCDC version (execute `cdc version`):
 [release-version=v5.2.3] [git-hash=a04ddac9fe83c8bdff267e4c44150060ea05f5ec] [git-branch=heads/refs/tags/v5.2.3] [utc-build-time="2021-11-26 07:39:58"] [go-version="go version go1.16.4 linux/amd64"]
```console
(paste TiCDC version here)
```

**Comment by lonng** [comment] 2021-12-30 08:05
I think it's a bug of TiUP-Cluster component, reference: https://github.com/pingcap/tiup/blob/934f837032b3d918b30268566b9b9ebfa4f0c479/pkg/cluster/spec/cdc.go#L168

```go
	if semver.Compare(clusterVersion, "v4.0.13") == -1 {
		if len(globalConfig)+len(instanceConfig) > 0 {
			return perrs.New("server_config is only supported with TiCDC version v4.0.13 or later")
		}
	}
```

**Comment by lonng** [comment] 2021-12-30 08:12
@AstroProfundis Can you assign this issue to somebody to help us fix it?

**Comment by AstroProfundis** [comment] 2021-12-30 08:18
@srstack PTAL

**Comment by overvenus** [comment] 2021-12-30 08:22
Does tiup trim "v" for "v5.4.0-nightly-20211221"? It may be related. See https://go.dev/play/p/kdSVGyxq7VF.

**Comment by lonng** [comment] 2021-12-30 08:24
@overvenus This bug is caused by `tiup cluster upgrade <cluster-name> nightly` and the `nightly` doesn't be mapped to actual cluster version `v5.4.0-nightly-20211221` correctly.

@Tammyxia  I have changed this bug to `severity/minor` because it's only affects the nightly version.

**Comment by srstack** [comment] 2021-12-30 17:45
@seiya-annie  
Can you tell me the version of TiUP?

**Comment by lonng** [comment] 2021-12-31 05:03
> @seiya-annie  
> Can you tell me the version of TiUP?

I think this bug exists all versions of tiup.

**Comment by srstack** [comment] 2021-12-31 05:34
> > @seiya-annie
> > Can you tell me the version of TiUP?
> 
> I think this bug exists all versions of tiup.

Yes, the nightly version number has been completed for the initconfig operation

**Comment by AstroProfundis** [comment] 2022-01-04 10:09
@seiya-annie Could you help verify if https://github.com/pingcap/tiup/pull/1702 fixes the problem?

**Closed** 2022-01-07 03:48 UTC
Labels: type/bug, severity/minor, found/automation, area/ticdc
