### ISSUE TITLE
"RowChangedEvent fallback row, ignore it" when injecting CDC and Kfaka consumer network partition

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tiflow#11237] opened 2024-06-04 04:14 UTC
### What did you do?

0. Topo:  Upstream TiDB --CDC-- Kafka -- Consumer -- MySQL
1. create Kafka open protocol changefeed: /cdc  cli  changefeed  create "--server=127.0.0.1:8301" "--sink-uri=kafka://downstream-kafka.cdc-kafka-controller-tps-7508966-1-706:9092/cdc_kafka_network_partition?replication-factor=2&max-message-bytes=1048576&protocol=open-protocol" "--changefeed-id=kafka-open-protocol-task-1
2. Run sysbench prepare
3. Run sysbench workload and at the same time inject CDC owner to Kafka controller network partition.
4. Run kafka consumer to consumer the kafka msg to MySQL 
5. Do data consistency check between TiDB and MySQL

### What did you expect to see?

Kafka consumer should not panic, and kafka msg consumed correctly and data consistency check passed.

### What did you see instead?

Consumer shoult not panic, and data consistency check passed betwen TiDB and MySQL

```
[writer.go:362] ["RowChangedEvent fallback row, ignore it"] [commitTs=450190641590173785] [watermark=450190655496913022] [partition=2] [row="{\"StartTs\":0,\"CommitTs\":450190641590173785,\"RowID\":0,\"PhysicalTableID\":0,
```

### Versions of the cluster

CDC : 350a2fb4596b489af648982082e60ea5735178ff
Consumer: c70aaf2590c0efcf4c8cce58d52ed88e7c20d287

**Comment by 3AceShowHand** [comment] 2024-06-05 09:06
This is caused by the message duplication, no message loss, this message can be ignored and does not affect eventual consistency.

We are going to investigate this issue further

**Comment by 3AceShowHand** [comment] 2024-07-11 08:39
This issue cannot be reproduced, close it. If reproduced, reopen this issue

**Closed by 3AceShowHand** 2024-07-11 08:39 UTC
Labels: type/bug, severity/major, area/ticdc, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, affects-7.5, may-affects-8.1
