### ISSUE TITLE
sorter engine report error on unmarshal data

### ISSUE THREAD

**Issue by 3AceShowHand** [pingcap/tiflow#8371] opened 2023-02-24 09:44 UTC
### What did you do?

Deploy a TiDB cluster on the MAC, by the following commands:

```
tiup playground v6.6.0 --db 1 --kv 1 --pd 1 --tiflash 0 --ticdc 1 --ticdc.binpath ./bin/cdc
```

### What did you expect to see?

nothing special

### What did you see instead?

```
[2023/02/24 14:48:08.635 +08:00] [ERROR] [manager.go:200] ["Worker handles sink task failed"] [namespace=default] [changefeed=kafka-test] [error="msgp: attempted to decode type \"int\" with method for \"map\""] [errorVerbose="msgp: attempted to decode type \"int\" with method for \"map\"\[ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/encoding.(*MsgPackGenSerde).Unmarshal\n\tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/encoding/value.go:45\ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventIter).Next\n\tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:363\ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine.(*MountedEventIter).readBatch\n\tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/mounted_iter.go:106\ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine.(*MountedEventIter).Next\n\tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/mounted_iter.go:63\ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTask\n\tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:311\ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTasks\n\tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:76\ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startWorkers.func1\n\tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:198\nruntime.goexit\n\truntime/asm_arm64.s:1172](http://ngithub.com/pingcap/errors.AddStack/n/tgithub.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174/ngithub.com/pingcap/errors.Trace/n/tgithub.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/juju_adaptor.go:15/ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/encoding.(*MsgPackGenSerde).Unmarshal/n/tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/encoding/value.go:45/ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventIter).Next/n/tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:363/ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine.(*MountedEventIter).readBatch/n/tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/mounted_iter.go:106/ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine.(*MountedEventIter).Next/n/tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/mounted_iter.go:63/ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTask/n/tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:311/ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTasks/n/tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:76/ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startWorkers.func1/n/tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:198/nruntime.goexit/n/truntime/asm_arm64.s:1172)"]
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

**Comment by overvenus** [comment] 2023-02-24 09:48
It might caused by corrupted data, as mention in https://github.com/tinylib/msgp/issues/173#issuecomment-273389260.

What's your environment?

**Comment by 3AceShowHand** [comment] 2023-02-24 10:03
> It might caused by corrupted data, as mentioned in [tinylib/msgp#173 (comment)](https://github.com/tinylib/msgp/issues/173#issuecomment-273389260).
> 
> What's your environment?

MAC M1, Ventura 13.0.1

**Comment by 3AceShowHand** [comment] 2023-03-02 08:51
This happens again on a Linux machine.

There is the steps:
```
tiup cluster deploy test-cluster v6.6.0

tiup cluster patch test-cluster -R cdc

tiup ctl:v6.6.0 create changefeed ...

tiup ctl:v6.6.0 pause changefeed ...

run some workload

tiup ctl:v6.6.0 resume changefeed ...
```
[cdc.log](https://github.com/pingcap/tiflow/files/10869335/cdc.log)

TiCDC is built by my development branch, named `kafka-client-benchmark`, the git hash is `4827c20ac48d23a507b59c5004413eab64466a62`

**Comment by 3AceShowHand** [comment] 2023-03-02 09:45
```unexpected fault address 0x7f1a628be986
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f1a628be986 pc=0x33cdfa9]

goroutine 5452 [running]:
runtime.throw({0x5bfbcab?, 0xc07be158b8?})
	runtime/panic.go:1047 +0x5d fp=0xc07be157d0 sp=0xc07be157a0 pc=0x1b4363d
runtime.sigpanic()
	runtime/signal_unix.go:851 +0x28a fp=0xc07be15830 sp=0xc07be157d0 pc=0x1b5a98a
github.com/tinylib/msgp/msgp.ReadMapHeaderBytes({0x7f1a628be986?, 0x70?, 0xc000600000?})
	github.com/tinylib/msgp@v1.1.6/msgp/read_bytes.go:166 +0x29 fp=0xc07be15868 sp=0xc07be15830 pc=0x33cdfa9
github.com/pingcap/tiflow/cdc/model.(*RawKVEntry).UnmarshalMsg(0xc060ab3490, {0x7f1a628be986?, 0x5989800?, 0x3f8211cf4f21ea01?})
	github.com/pingcap/tiflow/cdc/model/kv_gen.go:245 +0x30 fp=0xc07be158c8 sp=0xc07be15868 pc=0x39b7950
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/encoding.(*MsgPackGenSerde).Unmarshal(0xc00086e340?, 0xc076a0a360, {0x7f1a628be986?, 0x5d5?, 0x5d5?})
	github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/encoding/value.go:43 +0x94 fp=0xc07be158f8 sp=0xc07be158c8 pc=0x4a433d4
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventIter).Next(0xc02c378780)
	github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:361 +0x165 fp=0xc07be15970 sp=0xc07be158f8 pc=0x4a48b25
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine.(*MountedEventIter).readBatch(0xc01d46c000, {0x6550fc8, 0xc028be1400})
	github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/mounted_iter.go:106 +0x28e fp=0xc07be15a00 sp=0xc07be15970 pc=0x4a4112e
github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine.(*MountedEventIter).Next(0xc01d46c000, {0x6550fc8, 0xc028be1400})
	github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/mounted_iter.go:63 +0x3c fp=0xc07be15a60 sp=0xc07be15a00 pc=0x4a40c7c
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTask(0xc01bbbf0a0, {0x6550fc8, 0xc028be1400}, 0xc05c1f0850)
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:400 +0x8aa fp=0xc07be15da8 sp=0xc07be15a60 pc=0x4bf590a
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTasks(0x18?, {0x6550fc8, 0xc028be1400}, 0xc046b114a0)
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:77 +0xc5 fp=0xc07be15e20 sp=0xc07be15da8 pc=0x4bf3005
github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startWorkers.func1()
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:198 +0x90 fp=0xc07be15fe0 sp=0xc07be15e20 pc=0x4be1fb0
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc07be15fe8 sp=0xc07be15fe0 pc=0x1b7bc01
created by github.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startWorkers
	github.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:196 +0x47

```

**Comment by asddongmen** [comment] 2024-05-21 03:39
Fixed by https://github.com/pingcap/tiflow/pull/10899

**Closed by asddongmen** 2024-05-21 03:39 UTC
Labels: type/bug, severity/moderate, area/ticdc
